### ISSUE TITLE
Error in version >= 2.2.1 when working with eToken Certs

### ISSUE THREAD

**Issue by SnowLe0** [ancwrd1/snx-rs#23] opened 2024-06-11 15:04 UTC
Hello!

I came across a problem that when I switched to version snx-rs `>= 2.2.1` (both in gui and cli), the connection to the vpn server stopped being established.
Everything is fine with version `2.2.0`.
Perhaps PKCS11 initialization happens later now? (judging by the logs, the differences start from line 111)

I am attaching log files for versions `2.2.0` and `2.2.2`  (I had to anonymize some IPs, etc.)

[222.log](https://github.com/user-attachments/files/15790299/222.log)
[220.log](https://github.com/user-attachments/files/15790304/220.log)

**Comment by ancwrd1** [comment] 2024-06-11 18:47
thanks for reporting, a regression was unfortunately introduced and should be fixed now, please test from the main branch. I can't test it myself because I don't have access to the server with certificate authentication.

**Closed** 2024-06-11 19:22 UTC

**Comment by SnowLe0** [comment] 2024-06-12 16:23
Thank you very much!
With the new version everything works as it should.
Tested both on VPN servers with authorization based on certificates using eToken, and using login and password + MFA.
